name: ccsplit-app
options:
  bundleIdPrefix: com.negipo
  deploymentTarget:
    macOS: "13.0"
targets:
  ccsplit-app:
    type: application
    platform: macOS
    sources:
      - path: ccsplit-app
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.negipo.ccsplit-app
        INFOPLIST_FILE: ccsplit-app/Info.plist
        CODE_SIGN_ENTITLEMENTS: ccsplit-app/ccsplit_app.entitlements
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: ccsplit-app
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
  ccsplit-appTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ccsplit-appTests
    dependencies:
      - target: ccsplit-app
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ccsplit-app.app/Contents/MacOS/ccsplit-app"
        GENERATE_INFOPLIST_FILE: "YES"
