name: ccfocus
options:
  bundleIdPrefix: com.negipo
  deploymentTarget:
    macOS: "13.0"
packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
targets:
  ccfocus:
    type: application
    platform: macOS
    sources:
      - path: ccfocus
    dependencies:
      - package: KeyboardShortcuts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.negipo.ccfocus
        INFOPLIST_FILE: ccfocus/Info.plist
        CODE_SIGN_ENTITLEMENTS: ccfocus/ccfocus.entitlements
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: ccfocus
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
  ccfocusTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ccfocusTests
    dependencies:
      - target: ccfocus
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ccfocus.app/Contents/MacOS/ccfocus"
        GENERATE_INFOPLIST_FILE: "YES"
